version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      QDRANT_URL: qdrant
      QDRANT_PORT: 6333
      QDRANT_GRPC_PORT: 6334
      # QDRANT_API_KEY: your_qdrant_api_key
      QDRANT_COLLECTION: zqh
    ports:
      - "8080:8080"
    depends_on:
      - qdrant

  qdrant:
    image: generall/qdrant:latest
    ports:
      - "6333:6333"
      - "6334:6334"

