version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      DATASTORE: qdrant
      BEARER_TOKEN: 35c4afe3b6aa31bdf621e8cfbe008cadd940fe365ab8e01409e46b57222b7023
      OPENAI_API_KEY: ${OPENAI_API_KEY}
      QDRANT_URL: qdrant
      QDRANT_PORT: 6333
      QDRANT_GRPC_PORT: 6334
      # QDRANT_API_KEY: your_qdrant_api_key
      QDRANT_COLLECTION: zqh
    ports:
      - "8080:8080"
      - "3333:3333"
    depends_on:
      - qdrant

  qdrant:
    image: qdrant/qdrant:v1.3.2
    ports:
      - "6333:6333"
      - "6334:6334"
    volumes:
      - ./qdrant_storage:/qdrant/storage

